export const themeData = [
  {
    themeName: "Green Theme",
    primaryColor: "#76abae",
    secondaryColor: "#eeeeee",
    tertiryColor: "#222831",
  },
  {
    themeName: "Blue Theme",
    primaryColor: "#0074D9",
    secondaryColor: "#7FDBFF",
    tertiryColor: "#001f3f",
  },
  {
    themeName: "Red Theme",
    primaryColor: "#FF4136",
    secondaryColor: "#FFDC00",
    tertiryColor: "#85144b",
  },
  {
    themeName: "Purple Theme",
    primaryColor: "#B10DC9",
    secondaryColor: "#F012BE",
    tertiryColor: "#3D9970",
  },
  {
    themeName: "Orange Theme",
    primaryColor: "#FF851B",
    secondaryColor: "#FFB700",
    tertiryColor: "#FF4136",
  },
  {
    themeName: "Gray Theme",
    primaryColor: "#AAAAAA",
    secondaryColor: "#DDDDDD",
    tertiryColor: "#333333",
  },
  {
    themeName: "Teal Theme",
    primaryColor: "#39CCCC",
    secondaryColor: "#7FDBFF",
    tertiryColor: "#001f3f",
  },
  {
    themeName: "Sunset Theme",
    primaryColor: "#ff7e5f",
    secondaryColor: "#feb47b",
    tertiryColor: "#2d3748",
  },
  {
    themeName: "Forest Theme",
    primaryColor: "#2e8b57",
    secondaryColor: "#8fbc8f",
    tertiryColor: "#2f4f4f",
  },
  {
    themeName: "Ocean Theme",
    primaryColor: "#1e90ff",
    secondaryColor: "#87cefa",
    tertiryColor: "#4682b4",
  },
  {
    themeName: "Lavender Theme",
    primaryColor: "#9370db",
    secondaryColor: "#e6e6fa",
    tertiryColor: "#4b0082",
  },
  {
    themeName: "Autumn Theme",
    primaryColor: "#ff6347",
    secondaryColor: "#ffb6c1",
    tertiryColor: "#8b4513",
  },
  {
    themeName: "Spring Theme",
    primaryColor: "#00ff7f",
    secondaryColor: "#adff2f",
    tertiryColor: "#006400",
  },
  {
    themeName: "Chocolate Theme",
    primaryColor: "#d2691e",
    secondaryColor: "#f4a460",
    tertiryColor: "#8b4513",
  },
  {
    themeName: "Mint Theme",
    primaryColor: "#98ff98",
    secondaryColor: "#f5fffa",
    tertiryColor: "#2e8b57",
  },
  {
    themeName: "Peach Theme",
    primaryColor: "#ffdab9",
    secondaryColor: "#ffefd5",
    tertiryColor: "#ff7f50",
  },
  {
    themeName: "Sky Theme",
    primaryColor: "#87ceeb",
    secondaryColor: "#b0e0e6",
    tertiryColor: "#4682b4",
  },
  {
    themeName: "Sand Theme",
    primaryColor: "#c2b280",
    secondaryColor: "#f5deb3",
    tertiryColor: "#d2b48c",
  },
  {
    themeName: "Rose Theme",
    primaryColor: "#ffc0cb",
    secondaryColor: "#ffe4e1",
    tertiryColor: "#ff69b4",
  },
  {
    themeName: "Cherry Theme",
    primaryColor: "#de3163",
    secondaryColor: "#ffb6c1",
    tertiryColor: "#8b0000",
  },
  {
    themeName: "Lemon Theme",
    primaryColor: "#fff44f",
    secondaryColor: "#fafad2",
    tertiryColor: "#ffeb3b",
  },
  {
    themeName: "Violet Theme",
    primaryColor: "#ee82ee",
    secondaryColor: "#dda0dd",
    tertiryColor: "#8a2be2",
  },
  {
    themeName: "Wine Theme",
    primaryColor: "#722f37",
    secondaryColor: "#b04857",
    tertiryColor: "#3e1f22",
  },
  {
    themeName: "Emerald Theme",
    primaryColor: "#50c878",
    secondaryColor: "#2e8b57",
    tertiryColor: "#006400",
  },
  {
    themeName: "Pearl Theme",
    primaryColor: "#eae0c8",
    secondaryColor: "#fffaf0",
    tertiryColor: "#d4af37",
  },
  {
    themeName: "Slate Theme",
    primaryColor: "#708090",
    secondaryColor: "#778899",
    tertiryColor: "#2f4f4f",
  },
  {
    themeName: "Aqua Theme",
    primaryColor: "#00ffff",
    secondaryColor: "#e0ffff",
    tertiryColor: "#008080",
  },
];
